LITE-21474 Added optional cqrs-id argument to consume command
cloudblue/django-cqrs pull request #59
Opened 2021-12-19 08:35 UTC by maxipavlovic

2021-12-20 08:11 UTC, maxipavlovic commented
It's unreasonably hard to follow coverage rule in this case at this moment, so sonar report fails, though all integration tests are fine!

2021-12-20 09:01 UTC, net-free requested changes

2021-12-20 15:01 UTC, d3rky approved these changes

2021-12-20 17:55 UTC, maxipavlovic commented on dj_cqrs/transport/mock.py
> +    def consume(payload=None, **kwargs):
I think it's better to change as they may break now without the changes.

2021-12-20 17:57 UTC, maxipavlovic commented on dj_cqrs/management/commands/cqrs_consume.py
> +        parser.add_argument(
At first, I decided to skip validation. But as you wrote and the more I think on that, the more it makes sense. I will add validation.

2021-12-21 09:30 UTC, maxipavlovic commented on dj_cqrs/management/commands/cqrs_consume.py
> +        parser.add_argument(
Fixed

2021-12-21 10:32 UTC, net-free approved these changes

2021-12-21 10:43 UTC, zzzevaka approved these changes

2021-12-22 00:04 UTC, merged